// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZapVagas.Infrastructure.DataContext;

#nullable disable

namespace ZapVagas.Infrastructure.Migrations
{
    [DbContext(typeof(ZapVagasDbContext))]
    partial class ZapVagasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ZapVagas.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("ZapVagas.Domain.Entities.JobPreference", b =>
                {
                    b.Property<Guid>("PreferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PreferenceId");

                    b.HasIndex("CandidateId");

                    b.ToTable("JobPreferences", (string)null);
                });

            modelBuilder.Entity("ZapVagas.Domain.Entities.JobPreference", b =>
                {
                    b.HasOne("ZapVagas.Domain.Entities.Candidate", "Candidate")
                        .WithMany("JobPreferences")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("ZapVagas.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("JobPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
